src/Entity/BestBet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BestBetRepository")
 */
class BestBet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="text")
     */
    private ?string $text;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title;

    /**
     * @ORM\Column(type="date")
     */
    private $created;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $updated;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $link;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $image;

    /**
     * @ORM\Column(type="string", length=30, nullable=false, options={"default":"other"})
     */
    private string $source_type;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private ?string $source_identifier;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":false})
     */
    private ?bool $needs_update;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BestBetTerm", mappedBy="bestBet", cascade={"persist"})
     */
    private $terms;

    const SOURCE_TYPES = ['azlist', 'faq', 'other'];

    public function __construct()
    {
        $this->terms = new ArrayCollection();
        $this->setUpdated(new \DateTime('now'));
        if ($this->getCreated() === null) {
            $this->setCreated(new \DateTime('now'));
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getNeedsUpdate(): ?bool
    {
        return $this->needs_update;
    }

    public function setNeedsUpdate(?bool $needs_update): void
    {
        $this->needs_update = $needs_update;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return string
     */
    public function getSourceType(): string
    {
        return $this->source_type;
    }

    /**
     * @param string $source_type
     */
    public function setSourceType(string $source_type): void
    {
        if (!in_array($source_type, self::SOURCE_TYPES, true)) {
            throw new \InvalidArgumentException("\$source_type must be one of '" . implode("', '", self::SOURCE_TYPES) . "' : $source_type given");
        }
        $this->source_type = $source_type;
    }

    /**
     * @return ?string
     */
    public function getSourceIdentifier(): ?string
    {
        return $this->source_identifier;
    }

    /**
     * @param ?string $source_identifier
     */
    public function setSourceIdentifier(?string $source_identifier): void
    {
        $this->source_identifier = $source_identifier;
    }


    /**
     * @return Collection|BestBetTerm[]
     */
    public function getTerms(): Collection
    {
        return $this->terms;
    }

    public function addTerm(BestBetTerm $term): self
    {
        if (!$this->terms->contains($term)) {
            $this->terms[] = $term;
            $term->setBestBet($this);
        }

        return $this;
    }

    public function removeTerm(BestBetTerm $term): self
    {
        if ($this->terms->contains($term)) {
            $this->terms->removeElement($term);
            // set the owning side to null (unless already changed)
            if ($term->getBestBet() === $this) {
                $term->setBestBet(null);
            }
        }

        return $this;
    }

    public function sourceURL(): ?string
    {
        if ($this->source_type === 'azlist') {
            return "https://bc.libapps.com/libguides/az.php?action=0&section=2&id={$this->source_identifier}";
        } elseif ($this->source_type === 'faq') {
            return "https://answers.bc.edu/faq/{$this->source_identifier}";
        }
        return null;
    }
}

src/Form/BestBetType.php
<?php

namespace App\Form;

use App\Entity\BestBet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BestBetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $source_url = $builder->getData()->sourceURL() ? $builder->getData()->sourceURL() : null;
        $source_url_options = $source_url ? ['help' => "<a href='$source_url'>$source_url</a>", 'help_html' => true] : [];

        $builder
            ->add('title')
            ->add('text', TextareaType::class,['attr' => ['class' => 'best-bet-text']])
            ->add('link')
            ->add('image')
            ->add('source_type', ChoiceType::class, [
                'choices' => [
                    'AZ list entry' => 'azlist',
                    'FAQ question' => 'faq',
                    'Other' => 'other',
                ],
            ])
            ->add('source_identifier', TextType::class, $source_url_options)
            ->add('terms', CollectionType::class, [
                'entry_type' => BestBetTermType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => BestBet::class,
        ]);
    }
}

src/Controller/BestBetController.php
<?php

namespace App\Controller;

use App\Entity\BestBet;
use App\Form\BestBetType;
use App\Repository\BestBetRepository;
use App\Services\BestBetService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BestBetController extends AbstractController
{
    /**
     * @Route("/best-bet", name="best_bet_list")
     */
    public function list(BestBetRepository $repo, Request $request, PaginatorInterface $paginator)
    {
        $query = $repo->findAllQuery();
        $all = $paginator->paginate($query, $request->query->getInt('page', 1));

        return $this->render('best_bet/list.html.twig', [
            'betlist' => $all
        ]);
    }

    /**
     * @Route("/best-bet/new", name="best_bet_create")
     */
    public function new(Request $request, BestBetService $best_bet_client)
    {
        $bet = new BestBet();

        $form = $this->createForm(BestBetType::class, $bet);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $redirect = $this->processForm($form, 'created');
            $best_bet_client->add($bet);
            return $redirect;
        }

        return $this->render('best_bet/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/best-bet/{id}", name="best_bet_edit", methods={"GET","POST"})
     */
    public function edit(EntityManagerInterface $em, string $id, Request $request, BestBetService $best_bet_client)
    {
        $bet = $em->find(BestBet::class, $id);

        if (!$bet) {
            return $this->redirectWithFlash('best_bet_create', "Could not find best bet $id", 'warning');
        }

        $form = $this->createForm(BestBetType::class, $bet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $redirect = $this->processForm($form, 'edited');
            $best_bet_client->update($bet);
            return $redirect;
        }

        return $this->render('best_bet/edit.html.twig', [
            'bet' => $bet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/best-bet/{id}", name="best_bet_delete", methods={"DELETE"})
     */
    public function delete(Request $request, BestBet $bet, BestBetService $best_bet_client): RedirectResponse
    {
        if ($this->isCsrfTokenValid('delete' . $bet->getId(), $request->request->get('_token'))) {
            $bet_id = $bet->getId();

            $entityManager = $this->getDoctrine()->getManager();
            foreach ($bet->getTerms() as $term) {
                $entityManager->remove($term);
            }
            $entityManager->remove($bet);
            $entityManager->flush();

            $best_bet_client->delete($bet_id);
        }

        return $this->redirectToRoute('best_bet_list');
    }

    private function processForm(FormInterface $form, string $success_verb): RedirectResponse
    {
        $em = $this->getDoctrine()->getManager();

        /**
         * @var BestBet $bet
         */
        $bet = $form->getData();
        $em->persist($bet);
        $em->flush();

        $message = "Notification $success_verb";
        return $this->redirectWithFlash('best_bet_list', $message);
    }

    /**
     * @param string $route
     * @param string $message
     * @param string $status
     * @return RedirectResponse
     */
    private function redirectWithFlash(string $route, string $message, string $status = 'success'): RedirectResponse
    {
        $this->addFlash($status, $message);
        return $this->redirectToRoute($route);
    }
}

templates/best_bet/_delete_form.html.twig
<form method="post" action="{{ path('best_bet_delete', {'id': bet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/best_bet/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="row">
    <div class="notices-form-entry">

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>

        {{ form_end(form, {'render_rest': false}) }}
    </div>

    <div class="notices-form-instruction">
        <div class="instructions">
            <p>This <strong>best bet</strong> will be added to search results that match one of the <em>terms</em>.
            <p>The <em>title</em> is the clickable link that appears on the top of the best bet result.</p>
            <p>The <em>link</em> is an optional direct link to the resource.</p>
            <p>The <em>text</em> is the best bet content. Try to keep the text under 120 characters</p>
            <p>You can use
                <a href="https://help.github.com/en/articles/basic-writing-and-formatting-syntax">Markdown</a> to style your text, for example:
            <ul>
                <li><span class="markdown"><a href="https://www.bc.edu">[links](https://www.bc.edu)</a></span></li>
                <li><span class="markdown"><strong>**bold text**</strong></span></li>
                <li><span class="markdown"><em>italics</em></span></li>
            </ul>
            </p>
            <p>
                Best bets can have an optional <em>image</em>. Keep it small!
            </p>
            <p>
                The <em>source type</em> indicates where the entry was sourced from (LibGuides A-Z list, LibAnswers FAQ, etc.)
            </p>
            <p>
                The <em>source identifier</em> is the ID for the entry in its original source, e.g. the A-Z List resource ID number or FAQ question ID.
            </p>

        </div>
    </div>
</div>

templates/best_bet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Edit best bet
{% endblock %}

{% block icon %}
    <i class="fas fa-search-dollar"></i>
{% endblock %}

{% block body %}
    {{ include('best_bet/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('best_bet_list') }}" class="back-to-list">back to list</a>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/best_bet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BestBetController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/benjaminflorin/PhpstormProjects/symfony-notify/src/Controller/BestBetController.php'|file_link(0) }}">src/Controller/BestBetController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/benjaminflorin/PhpstormProjects/symfony-notify/templates/best_bet/index.html.twig'|file_link(0) }}">templates/best_bet/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/best_bet/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Best bets
{% endblock %}

{% block icon %}
    <i class="fas fa-search-dollar"></i>
{% endblock %}

{% block newbutton %}
    <a href="{{ path('best_bet_create') }}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">New
        best bet</a>
{% endblock %}

{% block body %}
    <table class="table">
        <thead>
        <tr>
            <th>Title</th>
            <th>URL</th>
            <th>Terms</th>
            <td class="action-td">&nbsp;</td>
        </tr>
        </thead>
        <tbody>
        {% for bet in betlist %}
            <tr{% if bet.needsUpdate %} class="needs-update"{% endif %}>
                <td><a href="{{ path('best_bet_edit', {'id': bet.id}) }}">{{ bet.title }}</a></td>
                <td>{{ bet.link |truncate(50) }}</td>
                <td>
                    {% for term in bet.terms %}
                        {{ term }}<br>
                    {% endfor %}
                </td>
                <td class="action-td">
                    {{ include('best_bet/_delete_form.html.twig') }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation">
        {{ knp_pagination_render(betlist) }}
    </div>
{% endblock %}

templates/best_bet/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('best_bet/_form.html.twig', {'button_label': 'Create'}) }}

    <a href="{{ path('template_index') }}" class="back-to-list">back to list</a>
{% endblock %}

{% block title %}
    Create a Best Bet
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}