src/Entity/Notification.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotificationRepository")
 */
class Notification
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $finish;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="notifications")
     */
    private $poster;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\NotificationView", mappedBy="notification", orphanRemoval=true)
     */
    private $views;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Priority", inversedBy="notifications")
     */
    private $priority;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NoteType", inversedBy="notifications")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Application", inversedBy="notifications")
     */
    private $application;

    /**
     * @ORM\Column(type="text")
     */
    private $parsed_text;

    /**
     * @ORM\Column(type="boolean")
     */
    private $autoposted = false;

    public function __construct()
    {
        $this->views = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $parser = new \Parsedown();
        $parser->setSafeMode(true);
        $this->text = $text;
        $this->setParsedText($parser->line($text));
        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getFinish(): ?\DateTimeInterface
    {
        return $this->finish;
    }

    public function setFinish(?\DateTimeInterface $finish): self
    {
        $this->finish = $finish;

        return $this;
    }

    public function getStartString()
    {
        return $this->start->format('Y-m-d H:i:s');
    }

    public function getFinishString()
    {
        return isset($this->finish) ? $this->finish->format('Y-m-d H:i:s') : null;
    }

    public function deactivate(): void
    {
        $this->finish = $this->now();
    }

    public function activate(): void
    {
        $this->finish = null;
        $this->start = $this->now();
    }

    public function isActive(): bool
    {
        $now = $this->now();

        if ($now < $this->start) {
            return false;
        }

        return !isset($this->finish) || $this->finish > $now;
    }

    public function isPending(): bool
    {
        return $this->start > $this->now();
    }

    private function now(): \DateTime
    {
        return new \DateTime('now', new \DateTimeZone('America/New_York'));
    }

    public function getPoster(): ?User
    {
        return $this->poster;
    }

    public function setPoster(?User $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function publicView(): array
    {
        return [
            'id'          => $this->id,
            'text'        => $this->text,
            'parsed_text' => $this->parsed_text,
            'priority'    => $this->getPriority() ? $this->getPriority()->getLevel() : 3,
            'type'        => $this->getType() ? $this->getType()->getName() : null,
            'application' => $this->getApplication() ? $this->getApplication()->getName() : null,
            'start'       => $this->getStartString(),
            'className'   => $this->isActive() ? 'fullcalendar-active-note' : '',
            'end'         => $this->getFinishString()
        ];
    }

    public function calendarFeed(string $route_base): array
    {
        $base = $this->publicView();

        $base['title'] = $base['text'];
        unset($base['text']);

        $base['url'] = "$route_base/{$this->id}";
        $base['color'] = 'white';

        if ($base['end'] === null) {
            $base['end'] = $base['start'];
        }

        return $base;
    }

    /**
     * @return Collection|NotificationView[]
     */
    public function getViews(): Collection
    {
        return $this->views;
    }

    public function addView(NotificationView $view): self
    {
        if (!$this->views->contains($view)) {
            $this->views[] = $view;
            $view->setNotification($this);
        }

        return $this;
    }

    public function removeView(NotificationView $view): self
    {
        if ($this->views->contains($view)) {
            $this->views->removeElement($view);
            // set the owning side to null (unless already changed)
            if ($view->getNotification() === $this) {
                $view->setNotification(null);
            }
        }

        return $this;
    }

    public function getPriority(): ?Priority
    {
        return $this->priority;
    }

    public function setPriority(?Priority $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getType(): ?NoteType
    {
        return $this->type;
    }

    public function setType(?NoteType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getApplication(): ?Application
    {
        return $this->application;
    }

    public function setApplication(?Application $application): self
    {
        $this->application = $application;

        return $this;
    }

    public function getParsedText(): ?string
    {
        return $this->parsed_text;
    }

    public function setParsedText(string $parsed_text): self
    {
        $this->parsed_text = $parsed_text;

        return $this;
    }

    public function loadFromTemlpate(Template $template)
    {
        $this->setApplication($template->getApplication());
        $this->setText($template->getText());
        $this->setPriority($template->getPriority());
        $this->setType($template->getType());
    }

    public function getAutoposted(): ?bool
    {
        return $this->autoposted;
    }

    public function setAutoposted(bool $autoposted): self
    {
        $this->autoposted = $autoposted;

        return $this;
    }

}

src/Entity/NotificationView.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotificationViewRepository")
 */
class NotificationView
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $timestamp;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Notification", inversedBy="views")
     * @ORM\JoinColumn(nullable=false)
     */
    private $notification;

    public function __construct()
    {
        $this->timestamp = new \DateTime('now', new \DateTimeZone('America/New_York '));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTimestamp(): ?\DateTimeInterface
    {
        return $this->timestamp;
    }

    public function setTimestamp(\DateTimeInterface $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    public function getNotification(): ?Notification
    {
        return $this->notification;
    }

    public function setNotification(?Notification $notification): self
    {
        $this->notification = $notification;

        return $this;
    }
}

src/Controller/NotificationController.php
<?php

namespace App\Controller;

use App\Entity\Notification;
use App\Entity\NotificationView;
use App\Entity\Template;
use App\Entity\User;
use App\Form\NotificationType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NotificationController extends AbstractController
{
    /**
     * @Route("/notification", name="notification_list")
     */
    public function list(EntityManagerInterface $em, PaginatorInterface $paginator, Request $request)
    {
        $repo = $em->getRepository(Notification::class);
        $closed_query = $repo->findClosedQuery();
        $closed = $paginator->paginate($closed_query, $request->query->getInt('page', 1));

        $active = $repo->findActiveNotifications();
        $pending = $repo->findPending();

        return $this->render(
            'notification/list.html.twig',
            ['closed' => $closed, 'active' => $active, 'pending' => $pending]
        );
    }

    /**
     * @Route("/active", name="notification_active_list")
     */
    public function listActive(EntityManagerInterface $em, Request $request)
    {
        $constraints = [
            'type' => $request->query->get('type'),
            'application' => $request->query->get('application')
        ];
	$notes = $em->getRepository(Notification::class)->findActiveNotifications($constraints);

        // If the user has not requested a single application (e.g. there coming from the homepage, where
        // multiple applications are covered), filter out any notices for applications that aren't intended
        // to be shown on the homepage.
        if (!$request->query->get('application')) {
            $notes = array_filter($notes, function (Notification $note) {
                if ($note->getApplication() && ! $note->getApplication()->getOnHomepage()) {
                    return false;
                }
                return true;
            });
	}
        return $this->buildJSONResponse($request, $notes);
    }

    /**
     * @Route("/pending", name="notification_pending_list")
     */
    public function listPending(EntityManagerInterface $em, Request $request)
    {
        $notes = $em->getRepository(Notification::class)->findPending();
        return $this->buildJSONResponse($request, $notes);
    }


    /**
     * @Route("/feed", name="notification_feed_list")
     */
    public function calendarFeed(EntityManagerInterface $em, Request $request)
    {
        $start = $request->get('start');
        $end = $request->get('end');
        $notes = $em->getRepository(Notification::class)->findByStartDate($start, $end);

        $response = [];
        foreach ($notes as $note) {
            $base = $this->generateUrl('notification_list');
            $response[] = $note->calendarFeed($base);
        }

        return $this->json($response);
    }

    /**
     * @Route("/notification/new", name="notification_create")
     */
    public function new(EntityManagerInterface $em, Request $request): Response
    {
        $blank_note = new Notification();

        if ($request->get('template')) {
            $template = $em->find(Template::class, $request->get('template'));
            $blank_note->setText($template->getText());
            $blank_note->setPriority($template->getPriority());
            $blank_note->setType($template->getType());
            $blank_note->setApplication($template->getApplication());
        }

        $blank_note->activate();
        $form = $this->createForm(NotificationType::class, $blank_note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            return $this->processForm($form, 'created');
        }

        return $this->renderEditForm($form, 'Create notification');
    }

    /**
     * @Route("/notification/search", name="notification_search", methods={"GET"})
     */
    public function search(EntityManagerInterface $em, PaginatorInterface $paginator, Request $request)
    {
        $term = $request->get('q', '');
        $query = $em->getRepository(Notification::class)->searchQuery($term);
        $notes = $paginator->paginate($query, $request->query->getInt('page', 1));
        return $this->render('notification/search.html.twig', ['notes' => $notes, 'query' => $term]);
    }

    /**
     * @Route("/notification/{id}", name="notification_edit", methods={"GET","POST"})
     */
    public function edit(EntityManagerInterface $em, string $id, Request $request)
    {
        $note = $em->find(Notification::class, $id);

        if (!$note) {
            return $this->redirectWithFlash('notification_create', "Could not find notification $id", 'warning');
        }

        $form = $this->createForm(NotificationType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            return $this->processForm($form, 'edited');
        }

        return $this->renderEditForm($form, 'Edit notification', $templates);
    }

    /**
     * @Route("/notification/{id}/deactivate", name="notification_deactivate", methods={"PUT"})
     */
    public function deactivate(EntityManagerInterface $em, $id, Request $request): Response
    {
        $note = $em->find(Notification::class, $id);

        if (!$note) {
            return $this->redirectWithFlash('notification_list', "Could not find $uid", 'warning');
        }

        $note->deactivate();
        $this->saveNote($note, $em);

        return $this->redirectToHomeOrList($request, 'Deactivated notification');
    }

    /**
     * @Route("/notification/{id}/delete", name="notification_delete", methods={"PUT"})
     */
    public function delete(EntityManagerInterface $em, $id, Request $request): Response
    {
        $note = $em->find(Notification::class, $id);

        if (!$note) {
            return $this->redirectWithFlash('notification_list', "Could not find $uid", 'warning');
        }

        $em->remove($note);
        $em->flush();

        return $this->redirectToHomeOrList($request, 'Deleted notification');
    }

    /**
     * @Route("/notification/{id}/activate", name="notification_activate", methods={"PUT"})
     */
    public function activate(EntityManagerInterface $em, $id, Request $request): Response
    {
        $note = $em->find(Notification::class, $id);

        if (!$note) {
            return $this->redirectWithFlash('notification_list', 'Could not find notification', 'warning');
        }

        $note->activate();
        $this->saveNote($note, $em);

        return $this->redirectWithFlash('notification_list', 'Activated notification');
    }

    /**
     * @Route("/notification/{id}/reactivate", name="notification_reactivate", methods={"PUT"})
     */
    public function reactivate(EntityManagerInterface $em, $id, Request $request): Response
    {
        $old_note = $em->find(Notification::class, $id);

        if (!$old_note) {
            return $this->redirectWithFlash('notification_list', 'Could not find notification', 'warning');
        }

        $new_note = new Notification();
        $new_note->setText($old_note->getText());
        $new_note->setPoster($this->currentUser());

        $new_note->activate();
        $this->saveNote($new_note, $em);

        return $this->redirectWithFlash('notification_list', 'Reactivated notification');
    }

    /**
     * @Route("/notification/{id}/copy", name="notification_copy")
     */
    public function copy(EntityManagerInterface $em, $id, Request $request): Response
    {
        $old_note = $em->find(Notification::class, $id);

        if (!$old_note) {
            return $this->redirectWithFlash('notification_create', "Could not find notification $id", 'warning');
        }

        $form = $this->createForm(NotificationType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            return $this->processForm($form, 'copied');
        }

        $form->get('text')->setData($old_note->getText());
        $form->get('start')->setData(new \DateTime('now', new \DateTimeZone('America/New_York')));

        return $this->renderEditForm($form, 'Create notification');
    }

    private function processForm(FormInterface $form, string $success_verb): RedirectResponse
    {
        $em = $this->getDoctrine()->getManager();

        $note = $form->getData();
        $note->setPoster($this->currentUser());
        $this->saveNote($note, $em);

        $message = "Notification $success_verb";
        return $this->redirectWithFlash('notification_list', $message);
    }

    /**
     * @param string $route
     * @param string $message
     * @param string $status
     * @return RedirectResponse
     */
    private function redirectWithFlash(string $route, string $message, string $status = 'success'): RedirectResponse
    {
        $this->addFlash($status, $message);
        return $this->redirectToRoute($route);
    }

    /**
     * @return User|object|null
     */
    private function currentUser()
    {
        $user = $this->getDoctrine()->getRepository(User::class)
            ->findOneBy(['uid' => 'florinb']);
        return $user;
    }

    /**
     * @param FormInterface $form
     * @param string $title
     * @return Response
     */
    private function renderEditForm(FormInterface $form, string $title = 'Edit notification'): Response
    {
        $templates = $this->getDoctrine()->getRepository(Template::class)->findAll();
        return $this->render(
            'notification/new.html.twig',
            [
                'form' => $form->createView(),
                'title' => $title,

templates/notification/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="row">
    <div class="notices-form-entry">
        {{ form_start(form, { 'attr': {'class': 'notices-edit-form'} }) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}
    </div>
    <div class="notices-form-instruction">
        <div class="instructions">
            <p>A <strong>notification</strong> is a notice to be added to the Libraries Web pages.
            <p>The <em>text</em> is the notice content. Try to keep the text under 120 characters</p>
            <p>You can use <a href="https://help.github.com/en/articles/basic-writing-and-formatting-syntax">Markdown</a> to style your text, for example:
            <ul>
                <li><span class="markdown"><a href="https://www.bc.edu">[links](https://www.bc.edu)</a></span></li>
                <li><span class="markdown"><strong>**bold text**</strong></span></li>
                <li><span class="markdown"><em>italics</em></span></li>
            </ul>
            </p>
            <p>A notice's <em>type</em> and optional <em>application</em> parameters are used in reporting.</p>
            <p>Notices with a high <em>priority</em> will display before or instead of notices with a lower priority. </p>
            <p>The notice will go out for display at the <em>start</em> time and stop displaying at the <end>time</end>. If you don't know when the notice will need to come down, don't enter an end date or time. </p>
        </div>
    </div>
</div>

templates/notification/_note_list.html.twig
<div class="row">
    <div class="col-12">
        <h3 class="note-status">{{ name|upper }}</h3>
        {% if notelist|length < 1 %}
            <div class="no-notifications">
                No {{ name }} notifications.
            </div>
        {% else %}
            <table class="table notifications-table">
                <thead>
                <tr>
                    <th>Message</th>
                    <th>
                        {% if paginate %}
                            {{ knp_pagination_sortable(closed, 'Start', 'n.start') }}
                        {% else %}
                            Start
                        {% endif %}
                    </th>
                    <th>End</th>
                    <th>Poster</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for notification in notelist %}
                    <tr class="{% if notification.isActive %}active{% endif %}">
                        <td>{{ notification.parsedText|raw }}</td>
                        <td>
                            {{ notification.startString }}</td>
                        <td>{{ notification.finishString }}</td>
                        <td>{% if notification.autoposted %}
                                Uptime Robot
                            {% else %}
                                {{ notification.poster.uid }}
                            {% endif %}
                        </td>
                        <td class="notification-actions">
                            {{ include('notification/actions.html.twig', {'notification':notification}) }}
                        </td>
                    </tr>
                {% endfor %}
                {% if paginate %}
                    <div class="navigation">
                        {{ knp_pagination_render(closed) }}
                    </div>
                {% endif %}
                </tbody>
            </table>
        {% endif %}
    </div>
</div>

templates/notification/actions.html.twig
<ul class="action-list">
    <li>
        {% if notification.isActive %}
            <form action="{{ path('notification_deactivate',{'id':notification.id}) }}"
                  method="POST"
                  class="deactivate-link"
            >
                <button>Deactivate</button>
                <input type="hidden" name="_method" value="PUT">
            </form>
        {% elseif notification.isPending %}
            <form action="{{ path('notification_activate',{'id':notification.id}) }}"
                  method="POST"
                  class="activate-link"
            >
                <button>Activate</button>
                <input type="hidden" name="_method" value="PUT">
            </form>
        {% else %}
            <form action="{{ path('notification_reactivate',{'id':notification.id}) }}"
                  method="POST"
                  class="reactivate-link"
            >
                <button>Reactivate</button>
                <input type="hidden" name="_method" value="PUT">
            </form>
        {% endif %}
    </li>
    {% if notification.isPending %}
        <li>
            <a href="{{ path('notification_edit', {'id':notification.id}) }}">Edit</a>
        </li>
    {% else %}
        <li>
            <a href="{{ path('notification_copy', {'id':notification.id}) }}">Repost</a>
        </li>
    {% endif %}
    {% if notification.isPending %}
        <li>
            <form action="{{ path('notification_delete',{'id':notification.id}) }}" method="POST">
                <button>Delete</button>
                <input type="hidden" name="_method" value="PUT">
            </form>
        </li>
    {% endif %}
</ul>

templates/notification/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block icon %}
    <i class="fas fa-exclamation-triangle"></i>
{% endblock %}

{% block body %}
    {% form_theme note_form 'bootstrap_4_layout.html.twig' %}

    {{ form_start(note_form, { 'attr': {'class': 'notices-edit-form'} }) }}
    {{ form_widget(note_form) }}
    <button type="submit" class="btn btn-primary">Submit</button>
    {{ form_end(note_form) }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datetime') }}
{% endblock %}

templates/notification/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notifications{% endblock %}

{% block stylesheets %}

{% endblock %}

{% block icon %}
    <i class="fas fa-exclamation-triangle"></i>
{% endblock %}

{% block newbutton %}
    <a href="{{ path('notification_create') }}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">New
        notification</a>
{% endblock %}

{% block body %}
    {% set active_params = {'name': 'active', 'notelist': active, 'paginate': false} %}
    {% include 'notification/_note_list.html.twig' with active_params  %}

    {% set pending_params = {'name': 'pending', 'notelist': pending, 'paginate': false} %}
    {% include 'notification/_note_list.html.twig' with pending_params %}

    {% set pending_params = {'name': 'closed', 'notelist': closed, 'paginate': true} %}
    {% include 'notification/_note_list.html.twig' with pending_params %}
{% endblock %}

templates/notification/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block icon %}
    <i class="fas fa-exclamation-triangle"></i>
{% endblock %}

{% block newbutton %}
    <div class="template-load-control">
        <label for="load-from-template">Load from template</label>
        <select name="load-from-template" id="load-from-template" onchange="location = this.options[this.selectedIndex].value;">
            <option>Select...</option>
            {% for template in templates %}
                <option value="{{ path('notification_create', {'template': template.id }) }}">{{ template.name }}</option>
            {% endfor %}
        </select>
    </div>
{% endblock %}

{% block body %}
    {{ include('notification/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('template_index') }}" class="back-to-list">back to list</a>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datetime') }}
{% endblock %}

templates/notification/populate.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NotificationController!{% endblock %}

{% block stylesheets %}
    <style>body {background-color: orange; }</style>
{% endblock %}

{% block body %}
    <style>
        .home-note-list { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .home-note-list code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1>Hello {{ controller_name }}! ✅</h1>

        This friendly message is coming from:
        <ul>
            <li>Your controller at <code><a href="{{ '/Users/benjaminflorin/PhpstormProjects/symfony-notify/src/Controller/NotificationController.php'|file_link(0) }}">src/Controller/NotificationController.php</a></code></li>
            <li>Your template at <code><a href="{{ '/Users/benjaminflorin/PhpstormProjects/symfony-notify/templates/notification/populate.html.twig'|file_link(0) }}">templates/notification/populate.html.twig</a></code></li>
        </ul>
    </div>
{% endblock %}

templates/notification/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search notifications{% endblock %}

{% block stylesheets %}

{% endblock %}

{% block icon %}
    <i class="fas fa-exclamation-triangle"></i>
{% endblock %}

{% block newbutton %}
    <a href="{{ path('notification_create') }}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">New
        notification</a>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <h3 class="note-status">Results for "{{ query }}"</h3>
            {% if notes|length < 1 %}
                <div class="no-notifications">
                    No pending notifications.
                </div>
            {% else %}
                <table class="table notifications-table">
                    <thead>
                    <tr>
                        <th>Message</th>
                        <th>{{ knp_pagination_sortable(notes, 'Start', 'n.start') }}</th>
                        <th>End</th>
                        <th>Poster</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for notification in notes %}
                        <tr class="{% if notification.isActive %}active{% endif %}">
                            <td>{{ notification.parsedText|raw }}</td>
                            <td>{{ notification.startString }}</td>
                            <td>{{ notification.finishString }}</td>
                            <td>{{ notification.poster.uid }}</td>
                            <td class="notification-actions">
                                {{ include('notification/actions.html.twig', {'notification':notification}) }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="navigation">
                    {{ knp_pagination_render(notes) }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}