src/Entity/Application.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApplicationRepository")
 */
class Application
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $uptime_robot_code;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Template", inversedBy="application", cascade={"persist", "remove"})
     */
    private $template;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="application")
     */
    private $notifications;

    /**
     * @ORM\Column(type="boolean")
     */
    private $automatic = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $on_homepage;

    /**
     * @ORM\Column(type="text")
     */
    private $public_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string")
     */
    private $public_name;

    public function __construct()
    {
        $this->on_homepage = false;
        $this->notifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUptimeRobotCode(): ?string
    {
        return $this->uptime_robot_code;
    }

    public function setUptimeRobotCode(?string $uptime_robot_code): self
    {
        $this->uptime_robot_code = $uptime_robot_code;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): self
    {
        $this->template = $template;

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setApplication($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getApplication() === $this) {
                $notification->setApplication(null);
            }
        }

        return $this;
    }

    public function getAutomatic(): ?bool
    {
        return $this->automatic;
    }

    public function setAutomatic(bool $automatic): self
    {
        $this->automatic = $automatic;

        return $this;
    }

    public function getOnHomepage(): ?bool
    {
        return $this->on_homepage;
    }

    public function setOnHomepage(bool $on_homepage): self
    {
        $this->on_homepage = $on_homepage;

        return $this;
    }

    public function getPublicDescription(): ?string
    {
        return $this->public_description;
    }

    public function setPublicDescription(string $public_description): self
    {
        $this->public_description = $public_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPublicName(): ?string
    {
        return $this->public_name;
    }

    public function setPublicName(string $public_name): self
    {
        $this->public_name = $public_name;

        return $this;
    }
}

src/Form/ApplicationType.php
<?php

namespace App\Form;

use App\Entity\Application;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApplicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('template')
            ->add(
                'uptime_robot_code',
                TextType::class,
                [
                    'label' => 'Uptime Robot code',
                    'required' => false
                ]
            )
            ->add(
                'on_homepage',
                CheckboxType::class,
                [
                    'label' => 'Show on homepage?',
                    'attr' => ['class' => 'show-on-homepage'],
                    'required' => false

                ]
            )
            ->add('public_name')
            ->add('public_description');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Application::class,
            ]
        );
    }
}

src/Controller/ApplicationController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Form\ApplicationType;
use App\Repository\ApplicationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/application")
 */
class ApplicationController extends AbstractController
{
    /**
     * @Route("/", name="application_index", methods={"GET"})
     */
    public function index(ApplicationRepository $applicationRepository): Response
    {
        return $this->render('application/index.html.twig', [
            'applications' => $applicationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="application_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $application = new Application();
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($application);
            $entityManager->flush();

            return $this->redirectToRoute('application_index');
        }

        return $this->render('application/new.html.twig', [
            'application' => $application,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="application_show", methods={"GET"})
     */
    public function show(Application $application): Response
    {
        return $this->render('application/show.html.twig', [
            'application' => $application,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="application_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Application $application): Response
    {
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('application_index', [
                'id' => $application->getId(),
            ]);
        }

        return $this->render('application/edit.html.twig', [
            'application' => $application,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="application_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Application $application): Response
    {
        if ($this->isCsrfTokenValid('delete'.$application->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($application);
            $entityManager->flush();
        }

        return $this->redirectToRoute('application_index');
    }
}

templates/application/_delete_form.html.twig
<form method="post" action="{{ path('application_delete', {'id': application.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ application.id) }}">
    <button class="btn">Delete</button>
</form>

templates/application/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="row">
    <div class="notices-form-entry">
        {{ form_start(form,  { 'attr': {'class': 'notices-edit-form'} }) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}
    </div>
    <div class="notices-form-instruction">
        <div class="instructions">
            <p><strong>Applications</strong> with templates will appear on the dashboard with a button for quickly posting a notification</p>
            <p>Choose a <em>name</em> for your application and chose a <em>template.</em></p>
            <p>Add the application's <em>Uptime Robot</em> monitor code if you want it's status tracked on the Dashboard.</p>
        </div>
    </div>
</div>

templates/application/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit application{% endblock %}

{% block icon %}
    <i class="fas fa-server"></i>
{% endblock %}

{% block body %}
    {{ include('application/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('application_index') }}" class="back-to-list">back to list</a>

    {{ include('application/_delete_form.html.twig') }}
{% endblock %}

templates/application/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Applications{% endblock %}

{% block icon %}
    <i class="fas fa-server"></i>
{% endblock %}

{% block newbutton %}
    <a href="{{ path('application_new') }}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">New
        application</a>
{% endblock %}

{% block body %}
    <table class="table applications-table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Uptime_robot_code</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for application in applications %}
            <tr>
                <td><a href="{{ path('application_edit', {'id': application.id}) }}">{{ application.name }}</a></td>
                <td>{{ application.uptimeRobotCode }}</td>
                <td>
                    {% if application.template %}
                        <a class="btn btn-danger btn-sm" href="{{ path('notification_create', {'template': application.template.id }) }}" role="button">Post</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/application/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New application{% endblock %}

{% block icon %}
    <i class="fas fa-server"></i>
{% endblock %}

{% block body %}

    {{ include('application/_form.html.twig') }}

    <a href="{{ path('application_index') }}" class="back-to-list">back to list</a>
{% endblock %}

templates/application/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application{% endblock %}

{% block icon %}
    <i class="fas fa-server"></i>
{% endblock %}

{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ application.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ application.name }}</td>
            </tr>
            <tr>
                <th>Uptime_robot_code</th>
                <td>{{ application.uptimeRobotCode }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('application_index') }}" class="back-to-list">back to list</a>

    <a href="{{ path('application_edit', {'id': application.id}) }}">edit</a>

    {{ include('application/_delete_form.html.twig') }}
{% endblock %}